name: 'sfdx'

#on: [push]
on: 
  push: 
    branches: [staging]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Master'
        uses: actions/checkout@v2              
      - name: Write the token into a file
        run: 'echo ${{ secrets.DEVHUB_TOKEN}} > token.txt'
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: 'Auth with the DevHub'
        #run: 'sfdx force:auth:sfdxurl:store -f token.txt -a DevHub -d'
        run: |
            echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
            sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
        env: 
            SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
      - name: 'Deploy'
        run: 'sfdx force:source:deploy -x manifest/package.xml -u anupam.tripathi@cunning-shark-k1xl4p.com'
        #run: 'sfdx force:mdapi:deploy -d manifest/ -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} -w 1' 
      - name : 'Create Scratch Org'
        run: 'sfdx force:org:create -f config/project-scratch-def.json -a my-scratch'
      - name: 'Push Code to Scratch Org'
        run: 'sfdx force:source:push -u my-scratch'
      - name: 'List all Orgs'
        run: 'sfdx force:org:list'
      - name: 'Delete Scratch Org'
        run: 'sfdx force:org:delete -u my-scratch --noprompt'
        