name: 'sfdx'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Master'
        uses: actions/checkout@main              
      - name: Write the token into a file
        run: 'echo ${{ secrets.DEVHUB_TOKEN}} > token.txt'
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: Auth with the DevHub
        run: 'sfdx force:auth:sfdxurl:store -f token.txt -a DevHub -d'
      - name: 'Deploy'
        run: 'sfdx force:source:deploy --sourcepath ./force-app/main/default -u anupam.tripathi@cunning-shark-k1xl4p.com'
      - name : 'Create Scratch Org'
        run: 'sfdx force:org:create -f config/project-scratch-def.json -a my-scratch'
      - name: 'Push Code to Scratch Org'
        run: 'sfdx force:source:push -u my-scratch'
      - name: 'List all Orgs'
        run: 'sfdx force:org:list'
      - name: 'Delete Scratch Org'
        run: 'sfdx force:org:delete -u my-scratch --noprompt'
        